In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pickle
import os
import seaborn as sns
from tqdm.auto import tqdm

/scratch/work/lyub2/.conda_envs/lb-env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 集大成！

In [12]:
# Initialize an empty DataFrame for the final resul
#df_a2 = pd.DataFrame(columns=['time_start_hour', 'time_start_hour_count', 'missing_counts', 'missing_percentage'])

# Define the path to the parent directory
parent_directory = '/scratch/work/lyub2/Problem_output_September/'

df_list = []

# Iterate through all 30 folders with tqdm for progress bar
for day in tqdm(range(1, 31), desc="Processing folders"):
    # Generate folder name in the format 'MMDD_output_csv' (e.g., '0901_output_csv')
    folder_name = f"09{str(day).zfill(2)}_output_csv"
    # Define the full path to the csv file
    file_path = os.path.join(parent_directory, folder_name, 'P1A2_missing_values_hour.csv')
    
    # Check if the file exists to avoid errors
    if not os.path.isfile(file_path):
        print(f"File not found: {file_path}")
        continue
    
    # Read the current CSV file
    df_current = pd.read_csv(file_path, usecols= ['time_start_hour', 'time_start_hour_count', 'missing_counts', 'missing_percentage'])

    
    # Append the current dataframe to the list
    df_list.append(df_current)

# Concatenate all dataframes in the list
df = pd.concat(df_list, ignore_index=True)

df_a2 = df.groupby('time_start_hour').agg({
    'time_start_hour_count': 'sum',
    'missing_counts': 'sum'
}).reset_index()

df_a2['missing_percentage'] = round((df_a2['missing_counts'] / df_a2['time_start_hour_count']) * 100, 2)

df_a2.to_csv('/scratch/work/lyub2/Problem_output_September/P1A2/df_a2.csv', index = False)

Processing folders: 100%|██████████| 30/30 [00:17<00:00,  1.70it/s]

In [14]:
df_a2

    time_start_hour  time_start_hour_count  missing_counts  missing_percentage
0               0.0                2790802          422588               15.14
1               1.0                1940789          253241               13.05
2               2.0                1412254          187266               13.26
3               3.0                1056464          134203               12.70
4               4.0                1253833          139798               11.15
5               5.0                3001445          237379                7.91
6               6.0                7809025          576169                7.38
7               7.0               15020203         1261081                8.40
8               8.0               19781979         1930567                9.76
9               9.0               14361199         1566704               10.91
10             10.0               12128767         1413820               11.66
11             11.0               14137054         1595977               11.29
12             12.0               15907949         1819117               11.44
13             13.0               17261345         1977180               11.45
14             14.0               20744848         2348704               11.32
15             15.0               24956022         2775866               11.12
16             16.0               27597050         3037760               11.01
17             17.0               24026041         2780915               11.57
18             18.0               20137359         2473809               12.28
19             19.0               16357901         2103537               12.86
20             20.0               14029590         1820192               12.97
21             21.0               10548814         1373301               13.02
22             22.0                6970297          905848               13.00
23             23.0                4398243          574904               13.07

In [15]:
h1 = pd.read_csv('/scratch/work/lyub2/Problem_output_September/0901_output_csv/P1A2_missing_values_hour.csv')

In [16]:
h1

,time_start_hour,missing_info,time_start_hour_count,missing_counts,missing_percentage
0,0,"[np.float64(1.0), np.float64(1.0), np.float64(...",193546,29782,0.153876
1,1,"[np.float64(1.0), np.float64(1.0), np.float64(...",142293,17562,0.123421
2,2,"[np.float64(1.0), np.float64(0.0), np.float64(...",109582,12569,0.114699
3,3,"[np.float64(1.0), np.float64(1.0), np.float64(...",23411,3004,0.128316
4,4,"[np.float64(1.0), np.float64(1.0), np.float64(...",32002,3227,0.100837
5,5,"[np.float64(1.0), np.float64(1.0), np.float64(...",128025,9078,0.070908
6,6,"[np.float64(1.0), np.float64(1.0), np.float64(...",343372,26281,0.076538
7,7,"[np.float64(1.0), np.float64(1.0), np.float64(...",667649,56283,0.084300
8,8,"[np.float64(0.0), np.float64(0.0), np.float64(...",866633,86133,0.099388
9,9,"[np.float64(1.0), np.float64(0.0), np.float64(...",584779,68584,0.117282
10,10,"[np.float64(1.0), np.float64(1.0), np.float64(...",452025,55416,0.122595
11,11,"[np.float64(1.0), np.float64(1.0), np.float64(...",524362,63968,0.121992
12,12,"[np.float64(1.0), np.float64(1.0), np.float64(...",609116,71313,0.117076
13,13,"[np.float64(0.0), np.float64(0.0), np.float64(...",703855,79932,0.113563
14,14,"[np.float64(1.0), np.float64(1.0), np.float64(...",876315,99579,0.113634
15,15,"[np.float64(1.0), np.float64(1.0), np.float64(...",1058410,118171,0.111650
16,16,"[np.float64(0.0), np.float64(0.0), np.float64(...",1163254,130160,0.111893
17,17,"[np.float64(1.0), np.float64(1.0), np.float64(...",1031994,118289,0.114622
18,18,"[np.float64(1.0), np.float64(1.0), np.float64(...",839176,102746,0.122437
19,19,"[np.float64(1.0), np.float64(1.0), np.float64(...",674104,86009,0.127590
20,20,"[np.float64(1.0), np.float64(1.0), np.float64(...",594048,79379,0.133624
21,21,"[np.float64(1.0), np.float64(0.0), np.float64(...",467995,63810,0.136348
22,22,"[np.float64(1.0), np.float64(0.0), np.float64(...",369225,49745,0.134728
23,23,"[np.float64(1.0), np.float64(1.0), np.float64(...",266126,34941,0.131295